[2024-06-11T11:17:01.460+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T11:17:01.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_word.process_file_length manual__2024-06-11T11:16:58.486409+00:00 map_index=0 [queued]>
[2024-06-11T11:17:01.514+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_word.process_file_length manual__2024-06-11T11:16:58.486409+00:00 map_index=0 [queued]>
[2024-06-11T11:17:01.524+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T11:17:01.539+0000] {taskinstance.py:2330} INFO - Executing <Mapped(PythonOperator): process_file_length> on 2024-06-11 11:16:58.486409+00:00
[2024-06-11T11:17:01.545+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6056) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T11:17:01.546+0000] {standard_task_runner.py:63} INFO - Started process 6059 to run task
[2024-06-11T11:17:01.546+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_word', 'process_file_length', 'manual__2024-06-11T11:16:58.486409+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/simple_hello_world.py', '--cfg-path', '/tmp/tmp1p1gzw1c', '--map-index', '0']
[2024-06-11T11:17:01.552+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask process_file_length
[2024-06-11T11:17:01.592+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_word.process_file_length manual__2024-06-11T11:16:58.486409+00:00 map_index=0 [running]> on host 678b3b027d57
[2024-06-11T11:17:01.718+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='hello_word' AIRFLOW_CTX_TASK_ID='process_file_length' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T11:16:58.486409+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T11:16:58.486409+00:00'
[2024-06-11T11:17:01.719+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T11:17:01.728+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T11:17:01.729+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_length() takes 1 positional argument but 65 were given
[2024-06-11T11:17:01.735+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hello_word, task_id=process_file_length, run_id=manual__2024-06-11T11:16:58.486409+00:00, map_index=0, execution_date=20240611T111658, start_date=20240611T111701, end_date=20240611T111701
[2024-06-11T11:17:01.746+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 131 for task process_file_length (get_length() takes 1 positional argument but 65 were given; 6059)
[2024-06-11T11:17:01.762+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T11:17:01.770+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
