[2024-06-12T05:51:17.975+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T05:51:18.004+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: invoice2receipt.merge_results manual__2024-06-12T05:50:09.273321+00:00 [queued]>
[2024-06-12T05:51:18.020+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: invoice2receipt.merge_results manual__2024-06-12T05:50:09.273321+00:00 [queued]>
[2024-06-12T05:51:18.024+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-12T05:51:18.054+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): merge_results> on 2024-06-12 05:50:09.273321+00:00
[2024-06-12T05:51:18.064+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5952) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T05:51:18.068+0000] {standard_task_runner.py:63} INFO - Started process 5953 to run task
[2024-06-12T05:51:18.068+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'invoice2receipt', 'merge_results', 'manual__2024-06-12T05:50:09.273321+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/invoice2receipt.py', '--cfg-path', '/tmp/tmp_v4pfnbk']
[2024-06-12T05:51:18.071+0000] {standard_task_runner.py:91} INFO - Job 357: Subtask merge_results
[2024-06-12T05:51:18.138+0000] {task_command.py:426} INFO - Running <TaskInstance: invoice2receipt.merge_results manual__2024-06-12T05:50:09.273321+00:00 [running]> on host 678b3b027d57
[2024-06-12T05:51:18.302+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='invoice2receipt' AIRFLOW_CTX_TASK_ID='merge_results' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T05:50:09.273321+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T05:50:09.273321+00:00'
[2024-06-12T05:51:18.304+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T05:51:18.306+0000] {logging_mixin.py:188} INFO - None
[2024-06-12T05:51:18.307+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-12T05:51:18.308+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T05:51:18.321+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=invoice2receipt, task_id=merge_results, run_id=manual__2024-06-12T05:50:09.273321+00:00, execution_date=20240612T055009, start_date=20240612T055118, end_date=20240612T055118
[2024-06-12T05:51:18.365+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-12T05:51:18.388+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T05:51:18.392+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
