[2024-06-11T21:26:16.926+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:26:16.940+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: invoice2receipt.read_inv_frm_S3 manual__2024-06-11T21:26:15.803021+00:00 [queued]>
[2024-06-11T21:26:16.948+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: invoice2receipt.read_inv_frm_S3 manual__2024-06-11T21:26:15.803021+00:00 [queued]>
[2024-06-11T21:26:16.949+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T21:26:16.965+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): read_inv_frm_S3> on 2024-06-11 21:26:15.803021+00:00
[2024-06-11T21:26:16.970+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=580) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T21:26:16.972+0000] {standard_task_runner.py:63} INFO - Started process 581 to run task
[2024-06-11T21:26:16.972+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'invoice2receipt', 'read_inv_frm_S3', 'manual__2024-06-11T21:26:15.803021+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/invoice2receipt.py', '--cfg-path', '/tmp/tmp6srcwxx3']
[2024-06-11T21:26:16.973+0000] {standard_task_runner.py:91} INFO - Job 221: Subtask read_inv_frm_S3
[2024-06-11T21:26:17.026+0000] {task_command.py:426} INFO - Running <TaskInstance: invoice2receipt.read_inv_frm_S3 manual__2024-06-11T21:26:15.803021+00:00 [running]> on host 678b3b027d57
[2024-06-11T21:26:17.119+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='invoice2receipt' AIRFLOW_CTX_TASK_ID='read_inv_frm_S3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:26:15.803021+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:26:15.803021+00:00'
[2024-06-11T21:26:17.121+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:26:17.122+0000] {logging_mixin.py:188} INFO - <***.providers.amazon.aws.hooks.s3.S3Hook object at 0x7f356e43d7f0>
[2024-06-11T21:26:17.131+0000] {base.py:84} INFO - Using connection ID 'AWS_connection' for task execution.
[2024-06-11T21:26:17.132+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='AWS_connection', conn_type='aws') credentials retrieved from login and password.
[2024-06-11T21:26:17.385+0000] {logging_mixin.py:188} INFO - ['sample1.json', 'sample2.json']
[2024-06-11T21:26:17.386+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-11T21:26:17.387+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:26:17.393+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=invoice2receipt, task_id=read_inv_frm_S3, run_id=manual__2024-06-11T21:26:15.803021+00:00, execution_date=20240611T212615, start_date=20240611T212616, end_date=20240611T212617
[2024-06-11T21:26:17.428+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-11T21:26:17.444+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:26:17.448+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
