[2024-06-11T12:16:46.550+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T12:16:46.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_word.processing_task_group.process_file manual__2024-06-11T12:16:44.842646+00:00 [queued]>
[2024-06-11T12:16:46.582+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_word.processing_task_group.process_file manual__2024-06-11T12:16:44.842646+00:00 [queued]>
[2024-06-11T12:16:46.583+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T12:16:46.597+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): processing_task_group.process_file> on 2024-06-11 12:16:44.842646+00:00
[2024-06-11T12:16:46.602+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6874) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T12:16:46.603+0000] {standard_task_runner.py:63} INFO - Started process 6875 to run task
[2024-06-11T12:16:46.603+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_word', 'processing_task_group.process_file', 'manual__2024-06-11T12:16:44.842646+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/simple_hello_world.py', '--cfg-path', '/tmp/tmp_cklfbxd']
[2024-06-11T12:16:46.604+0000] {standard_task_runner.py:91} INFO - Job 143: Subtask processing_task_group.process_file
[2024-06-11T12:16:46.640+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_word.processing_task_group.process_file manual__2024-06-11T12:16:44.842646+00:00 [running]> on host 678b3b027d57
[2024-06-11T12:16:46.705+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='hello_word' AIRFLOW_CTX_TASK_ID='processing_task_group.process_file' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T12:16:44.842646+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T12:16:44.842646+00:00'
[2024-06-11T12:16:46.706+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T12:16:46.715+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T12:16:46.716+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: read_file() missing 1 required positional argument: 'filename'
[2024-06-11T12:16:46.724+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hello_word, task_id=processing_task_group.process_file, run_id=manual__2024-06-11T12:16:44.842646+00:00, execution_date=20240611T121644, start_date=20240611T121646, end_date=20240611T121646
[2024-06-11T12:16:46.735+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 143 for task processing_task_group.process_file (read_file() missing 1 required positional argument: 'filename'; 6875)
[2024-06-11T12:16:46.778+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T12:16:46.810+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T12:16:46.817+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
