[2024-06-12T05:11:57.861+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T05:11:57.889+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: invoice2receipt.read_inv_from_S3 manual__2024-06-12T05:11:56.101833+00:00 [queued]>
[2024-06-12T05:11:57.903+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: invoice2receipt.read_inv_from_S3 manual__2024-06-12T05:11:56.101833+00:00 [queued]>
[2024-06-12T05:11:57.906+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-12T05:11:57.932+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): read_inv_from_S3> on 2024-06-12 05:11:56.101833+00:00
[2024-06-12T05:11:57.940+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5607) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T05:11:57.948+0000] {standard_task_runner.py:63} INFO - Started process 5608 to run task
[2024-06-12T05:11:57.947+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'invoice2receipt', 'read_inv_from_S3', 'manual__2024-06-12T05:11:56.101833+00:00', '--job-id', '317', '--raw', '--subdir', 'DAGS_FOLDER/invoice2receipt.py', '--cfg-path', '/tmp/tmpmwx0an7t']
[2024-06-12T05:11:57.954+0000] {standard_task_runner.py:91} INFO - Job 317: Subtask read_inv_from_S3
[2024-06-12T05:11:58.049+0000] {task_command.py:426} INFO - Running <TaskInstance: invoice2receipt.read_inv_from_S3 manual__2024-06-12T05:11:56.101833+00:00 [running]> on host 678b3b027d57
[2024-06-12T05:11:58.177+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='invoice2receipt' AIRFLOW_CTX_TASK_ID='read_inv_from_S3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T05:11:56.101833+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T05:11:56.101833+00:00'
[2024-06-12T05:11:58.179+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T05:11:58.181+0000] {logging_mixin.py:188} INFO - <***.providers.amazon.aws.hooks.s3.S3Hook object at 0x7f356e474260>
[2024-06-12T05:11:58.194+0000] {base.py:84} INFO - Using connection ID 'AWS_connection' for task execution.
[2024-06-12T05:11:58.196+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='AWS_connection', conn_type='aws') credentials retrieved from login and password.
[2024-06-12T05:11:58.615+0000] {python.py:237} INFO - Done. Returned value was: ['sample-invoice-1.pdf', 'sample-invoice-2.pdf']
[2024-06-12T05:11:58.615+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T05:11:58.668+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=invoice2receipt, task_id=read_inv_from_S3, run_id=manual__2024-06-12T05:11:56.101833+00:00, execution_date=20240612T051156, start_date=20240612T051157, end_date=20240612T051158
[2024-06-12T05:11:58.692+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-12T05:11:58.915+0000] {taskinstance.py:3503} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-06-12T05:11:58.922+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
